name: cine_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  card_swiper: ^3.0.1
  animate_do: ^3.3.7
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
